### ISSUE TITLE
Hoy can i use a filter for options?

### ISSUE THREAD

**Issue by joseescaballero** [inmagik/ionic-modal-select#18]
I would like to use filter in options. Something like

 <button class="button button-assertive" modal-select="" ng-model="someSetModel" options="selectableNames | filter:myFilter" option-property="name">

¿how can i use?. I saw the option "use-collection-repeat" but no examples.

thanks

**Comment by bianchimro** [comment]
`options` must be an array, and not an expression like those used in ng-repeat or collection-repeat directives.

"use-collection-repeat" does another thing: it forces rendering the options list with  ionic collection-repeat instead of angular ng-repeat.

As of now, you must filter the options before passing them to directive.

Anyway, I think it's a good idea to pass the "repeater" expression to the directlve.
I'm closing this issue and opening one for this use case.

**Comment by bianchimro** [comment]
see #19

**Comment by joseescaballero** [comment]
Perfect. I hope you improve soon.

Thanks

Un cordial saludo

Pepe Caballero

**Comment by bianchimro** [comment]
hey @joseescaballero what you asked should be doable now, using `options-expression` attribute instead of `options`. see also the exampled named "repeat expression with filter" in the current test codepen: http://codepen.io/bianchimro/pen/epYYQO?editors=101

best regards
Mauro

**Comment by joseescaballero** [comment]
Perfect!! it works now.

thanks too much

Un cordial saludo

Pepe Caballero
