### ISSUE TITLE
Use on <select>

### ISSUE THREAD

**Issue by SimpleDeveloper49** [inmagik/ionic-modal-select#45]
The documentation states

> The element you use this directive must be clickable.

any chance we could get this to work for a <select> tag or are there any technical limitations why this is not possible?

**Comment by bianchimro** [comment]
hi @SimpleDeveloper49 ,
the limitation is due to the current implementation of the modal opening.
see lines around:

https://github.com/inmagik/ionic-modal-select/blob/master/src/ionic-modal-select.js#L316

The modal is opened like this
```
iElement.on('click', function(){
  //code to open modal here
}
```
(`iElement` is the element the directive is applied to)

Seems like this is not working on some tags, but If you have some suggestions to overcome this limitation that would be great.
Probably this is due to the fact that some tags (like `select`) stops the propagation of the click event before it can be handled by the directive. (select has normally its own behavior on click)

I also had the same problem at the beginning of the development, as the directive was born to replace `select` tags, but in the end I found that I could replace it with a `button` with the same - or even better -  user experience. One option would be replace dynamically the `select` from inside the directive, or maybe "overlap" it with something clickable, but it's a bit too specific in my opinion.

If you have some use case that forces you to use the directive on a `select` tag let me know, otherwise I am going to close this as I did not found a viable solution so far.

Best regards
Mauro

**Comment by SimpleDeveloper49** [comment]
@bianchimro,  

I'd say that it is purely a UI/UX consideration. I was looking for an easier way to style the drop down list option for mobile experience. 

I agree, the difference in behaviour are a technical difficulty. It would be probably easier to create a custom directive element to achieve this. Given that this is not the direction this project is going, I am okay with closing this.

I did run across something that might get closer to what I envisioned: 
https://github.com/angular-ui/ui-select 

Thanks again, and good job on the plugin!
